language: php

php:
  - 7.3

install:
  - travis_retry composer self-update && composer --version
  - travis_retry composer update --no-interaction

script:
  - vendor/bin/phpstan analyze ./src --level 7 --ansi
